### ISSUE TITLE
i got issue while running xerosploit thiss tool is asking for 

### ISSUE THREAD

**Issue by HackBaker** [Vijay-Mahajan/XeroSploit-Installer#1]

**Comment by HackBaker** [comment]
File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by HackBaker** [comment]
when i run command apt install python-pip 
it shows 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate

**Comment by HackBaker** [comment]
please help

**Comment by CrazyIndianDeveloper** [comment]
i am just updated new commands. now this issue fixed
