### ISSUE TITLE
No module named terminaltables

### ISSUE THREAD

**Issue by Lefixy** [Vijay-Mahajan/XeroSploit-Installer#2]
Hi, I ran the script, it seems to be successful, but when I run the command

$xerosploit

it show:

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

How can I solve?

**Comment by santhoshsandu** [comment]
i also have the same problem

**Comment by shabari2003** [comment]
type this pip command in your terminal

pip install terminaltables

it can solve your problem
